In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [44]:
nt = 50           # number of temperature points
N=10              # size of lattice, N x N
eqsteps = 2000    # number of MC sweeps for equilibration
mcsteps = 2500    # number of MC sweeps for calculation

T = np.linspace(1.53, 3.28, nt)
Energy, Magnetization, SpecificHeat, Susceptibility = np.zeros(nt), np.zeros(nt), np.zeros(nt), np.zeros(nt)

In [97]:
a = np.random.randint(0, N)
b = np.random.randint(0, N)
s =  state[a, b]
nb = state[(a+1)%N,b] + state[(a-1)%N,b] + state[a,(b+1)%N] + state[a,(b-1)%N]

In [6]:
state = 2*np.random.randint(2,size=(N,N))-1
print(state) 

[[-1  1 -1 -1 -1  1  1  1  1  1]
 [ 1  1  1 -1  1 -1 -1  1 -1  1]
 [ 1 -1 -1  1 -1  1  1  1 -1 -1]
 [ 1 -1  1  1 -1 -1  1 -1  1  1]
 [ 1  1  1  1 -1  1  1  1 -1  1]
 [ 1 -1 -1  1 -1 -1  1  1  1 -1]
 [ 1  1  1 -1  1 -1 -1 -1 -1  1]
 [-1 -1  1 -1 -1 -1  1 -1  1 -1]
 [ 1 -1 -1 -1 -1  1  1 -1  1 -1]
 [ 1 -1 -1  1 -1  1  1 -1 -1 -1]]
