In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [1]:
N=10

In [7]:
state = 2*np.random.randint(2,size=(N,N))-1
print(state) 

[[ 1  1 -1 -1  1  1 -1 -1 -1 -1]
 [ 1  1  1  1 -1  1 -1  1  1  1]
 [-1  1  1  1 -1 -1  1  1  1  1]
 [-1  1  1  1 -1  1  1  1  1  1]
 [ 1  1 -1 -1  1  1 -1 -1  1 -1]
 [-1  1  1 -1 -1 -1 -1 -1  1  1]
 [-1 -1  1  1 -1 -1 -1  1 -1 -1]
 [ 1 -1 -1  1  1  1  1 -1  1 -1]
 [ 1 -1 -1 -1  1 -1 -1  1  1  1]
 [ 1  1  1  1 -1  1 -1 -1  1 -1]]
